def generate_response(question: str) -> str:
    """
    Temporary LLM response function.
    Later, this function will call Ollama / Llama model.
    """

    if not question.strip():
        return "Please enter a healthcare-related question."

    return (
        "This is a temporary AI response. "
        "Later, this answer will be generated by a local LLM with RAG. "
        f"Your question was: {question}"
    )